# Generated by Django 3.0 on 2020-03-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0002_newstext'),
    ]

    operations = [
        migrations.CreateModel(
            name='googleNewsHeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('link', models.TextField()),
                ('published_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='newsText',
        ),
    ]
