# Generated by Django 3.0 on 2020-03-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0003_auto_20200326_1140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='googleNewsHeadline',
            new_name='googleNewsHeadlineCOV',
        ),
    ]
