# Generated by Django 3.0 on 2020-02-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=32)),
                ('news_text', models.TextField()),
            ],
        ),
    ]
